services:
  bot_db:
    image: postgres:15-alpine
    container_name: bot_db
    networks:
      - bot_network
    env_file:
      - .env.production
    volumes:
      - bot_app_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bot_user}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

    mem_limit: 300m
    mem_reservation: 150m

    logging:
      options:
        max-size: "10m"
        max-file: "5"

  bot_app:
    image: artemtsurukin/eng_words_bot:1.1
    container_name: bot_app
    networks:
      - bot_network
    env_file:
      - .env.production
    depends_on:
      bot_db:
        condition: service_healthy
    restart: unless-stopped

    mem_limit: 200m
    mem_reservation: 100m

    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_app_data:

networks:
  bot_network:
    driver: bridge